import type { MetadataRoute } from "next";
import { siteInfo } from "@/lib/content";

// Icons are generated by scripts/generate-brand-assets.py.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteInfo.name,
    short_name: siteInfo.name,
    description: siteInfo.description,
    start_url: "/",
    display: "standalone",
    background_color: "#fbfbfe",
    theme_color: "#fbfbfe",
    icons: [
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/brand/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
